### ISSUE TITLE
密码文件改名请问具体是怎样改名

### ISSUE THREAD

**Issue by xixi-furry** [zfile-dev/zfile#12]
有没有规定的格式呢？

**Comment by zhaojun1998** [comment]
没有，只要改了配置文件中

```yml
zfile:
  cache:
    timeout: 300
  constant:
    header: header.md
    password: password.txt     ---这里的文件名即可
```
