### ISSUE TITLE
建议增加自定义footer设置

### ISSUE THREAD

**Issue by Mhy278** [zfile-dev/zfile#294]
国内要求底部展示备案号及工信部跳转，但并没有在zfile配置文件、前端和后台设置中找到相关的设置，不过发现zfile演示站底部有展示备案号，因此建议增加自定义footer设置，位置建议应该在readme.md之下，谢谢大佬。

**Comment by zhaojun1998** [comment]
我那个备案号是通过自定义 JS 和 CSS 实现的：

自定义 CSS：
```css
.footer,
.footer a {
    text-align: center;
    background-color: transparent;
    color: #555;
}
```

自定义 JS：
```javascript
$("#List").append("<div class='footer'><a href='https://beian.miit.gov.cn/' target='_blank'>冀ICP备17004571号</a></div>")
```
