### ISSUE TITLE
备案号

### ISSUE THREAD

**Issue by zranl** [zfile-dev/zfile#322]
能在页面底部增加一个备案号吗

**Comment by zhaojun1998** [comment]
目前版本可以使用如下方式增加，下版本会增加配置项

自定义 JS 添加：
```javascript
$("#List").append("<div class='footer'><a href='https://beian.miit.gov.cn/' target='_blank'>你的备案号</a></div>")
```

自定义 CSS 添加：
```css
.footer,
.footer a {
    text-align: center;
    background-color: transparent;
    color: #555;
}
```
