### ISSUE TITLE
业外人员，弱弱的问下各位大佬，如何自定义CSS宽度~

### ISSUE THREAD

**Issue by i-iooi-i** [zfile-dev/zfile#330]
尝试着自定义了一下宽度，把顶栏的宽度也一起自定义了~ 
只想自定义文件夹列表的宽度，谢谢。

**Comment by zhaojun1998** [comment]
1. 后台设置中这里有个选项，设置后文件取默认占用 75% 的宽度，两边各留白 12.5%。（仅 PC 端生效）
<img width="595" alt="image" src="https://user-images.githubusercontent.com/35387985/156733023-257fa453-9f94-4c0b-9adb-d10e6756e2da.png">

2. 如上面的默认 75 的选项，无法满足你的要求，可以自动增加自定义 css，示例：
```css
@media only screen and (min-width: 1200px) {
    .el-row .el-col-lg-18 {
        width: 90%;
    }

    .el-col-offset-3 {
        margin-left: 5%;
    }
}
```

注：此 css 仅当 `页面布局` 选择了步骤一种的 `居中` 时才会生效，上述代码将占用 90% 的宽度，且距离左侧 5%，也就是居中。你可以自行调整这两个数值的比例来达到你想要的结果。
