### ISSUE TITLE
添加onedrive 获取令牌时 400

### ISSUE THREAD

**Issue by AlliotTech** [zfile-dev/zfile#396]
hello, 当我准备添加Onedrive的时候，出现了400的情况，如下是我的配置文件与nginx conf：  
response:  
HTTP Error 400. The request is badly formed.

``` yaml
version: '3.3'
services:
    zfile:
        container_name: zfile
        restart: always
        ports:
            - '18080:8080'
        volumes:
            - '/zfile/db:/root/.zfile-v4/db'
            - '/zfile/logs:/root/.zfile-v4/logs'
        image: zhaojun1998/zfile

```

``` conf
    location / {
        proxy_pass http://localhost:18080;
        proxy_redirect default;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        if  ($http_user_agent ~*  "bot|spider" ) {
            access_log off;
        }
```
