### ISSUE TITLE
Minio 做后台，可以创建文件夹，无法上传文件

### ISSUE THREAD

**Issue by yzpopulation** [zfile-dev/zfile#420]
Minio 做后台，可以创建文件夹、删除文件夹，无法上传文件
![image](https://user-images.githubusercontent.com/12810531/183397875-0d9caa9d-9ff3-4145-b5d8-e1d215c7096d.png)
![image](https://user-images.githubusercontent.com/12810531/183398261-bb227e53-272a-4c9f-a629-0fe959e462d1.png)

**Comment by zhaojun1998** [comment]
@yzpopulation 

我在自己的环境进行了测试，发现没有问题。
麻烦提供下 F12 控制台截图，看看有没有报错，还有方便的话，最好提供下 zfile 地址，我去看看。

**Comment by yzpopulation** [comment]
好像是因为不知内部地址，及https问题，Minio 和 Zfile 我都是用的docker，对外只有一个nginx 进行反代
外部和172.16.0.0/24 是不通的
![屏幕截图 2022-08-09 145458](https://user-images.githubusercontent.com/12810531/183584583-51e1e475-a7df-4772-a96c-50540195a6c1.png)

**Comment by zhaojun1998** [comment]
浏览器限制，如果您的主站点，在当前场景下也就是 zfile 站点是 https 的，那个，在这个网站中，必须引用 https 的资源，也就是你的 minio 必须是 https 的。这个是浏览器安全限制。

你这里 minio 地址应该写 https 的，可以通过 nginx 再反向代理一下，并配置上 https 证书。

**Comment by yzpopulation** [comment]
还有一个问题，我的Minio和zfile  nginx 同属于一个docker 下的network ，对外只有一个nginx 服务，然而在上传文件时，好像是直接通过浏览器对接 minio 接口，并不是通过后台java 转存，因此无法使用docker 内部IP 作为服务地址，这个问题能否进行修复？

**Comment by zhaojun1998** [comment]
您应该从容器中对外暴露两个访问端口，docker 是支持这个功能的，按照您上面提供的架构图，是这三个都在一个 docker 镜像中？还是 docker-compose 还是什么情况。

minio 没有采用转存是因为可能不是在一个服务器上，如果不在一个服务器上，用 java 中转的话，就会造成额外的性能损耗。

**Comment by yzpopulation** [comment]
``docker network create --driver=bridge --subnet=172.16.0.1/24 --gateway=172.16.0.1 npm``
``` 
services:
  app: 
    image: jc21/nginx-proxy-manager:2.9.18
    container_name: npm
    hostname: npm
    restart: unless-stopped
    dns:
      - 114.114.114.114
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
      - ./config.json:/app/config/production.json
    networks:
      npm:
        ipv4_address: 172.16.0.2
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
networks:
  npm:
    external: true
```
```
services:
  app: 
    image: bitnami/minio:latest
    container_name: minio
    hostname: minio
    restart: unless-stopped
    dns:
      - 114.114.114.114
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root
    networks:
      npm:
        ipv4_address: 172.16.0.8
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5

networks:
  npm:
    external: true
```
```
services:
  app: 
    image: zhaojun1998/zfile
    container_name: zfile
    hostname: zfile
    restart: unless-stopped
    dns:
      - 114.114.114.114
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '/root/zfile/db:/root/.zfile-v4/db'
      - '/root/zfile/logs:/root/.zfile-v4/logs'
    networks:
      npm:
        ipv4_address: 172.16.0.7
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 5
networks:
  npm:
    external: true
```

先建一个docker 网络，然后三个dockercompose ，利用npm进行反向代理，自签名
能否添加在一个服务器上的操作
