### ISSUE TITLE
S3通用协议为私有空间时生成链接问题

### ISSUE THREAD

**Issue by D3CODING** [zfile-dev/zfile#43]
使用S3通用协议且为私有空间时，默认生成的链接`X-Amz-Expires`字段为300，即链接300秒后过期，对大文件和在线播放音视频不太友好。
希望在下个版本中，当S3为私有空间时能新增一个框填链接过期时间（S3协议`X-Amz-Expires`最大可以604800，也就是7天）。

**Comment by zhaojun1998** [comment]
@lichenzero  

目前配置文件是支持修改这个时间的：

```yml
zfile:
  cache:
    timeout: 300
```
