### ISSUE TITLE
docker容器4.3.1版本升级错误

### ISSUE THREAD

**Issue by wesmile8** [zfile-dev/zfile#756]
### 4.3.1版本Docker容器不断重启

Docker部署zfile4.3.0版本，使用watchtower更新至4.3.1版本后，容器不断重启报错，日志如所示：

```
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
standard_init_linux.go:230: exec user process caused: exec format error
``` 

我的Docker compose配置：
```
version: '3.9'
services:
    zfile:
        image: zhaojun1998/zfile
        volumes:
            - '/volume2/Datas:/data/file'
            - '/volume1/docker/zfile/logs:/root/.zfile-v4/logs'
            - '/volume1/docker/zfile/db:/root/.zfile-v4/db'
        ports:
            - '18383:8080'
        restart: always
        container_name: zfile
```
