### ISSUE TITLE
文件名称包含中文, 短链 302 跳转无法编码

### ISSUE THREAD

**Issue by tointcn** [zfile-dev/zfile#763]
```log
zfile  | 2025-06-16 01:08:00.129  WARN 1 --- [                                    ] [          ] [               ] [io-8080-exec-37] o.apache.coyote.http11.Http11Processor   175    : The HTTP response header [Location] with value [https://x.cn/插件应用.pdf] has been removed from the response because itlid
zfile  |
zfile  | java.lang.IllegalArgumentException: The Unicode character [插] at code point [25,554] cannot be encoded as it is outside the permitted range of 0 to 255
zfile  |        at org.apache.tomcat.util.buf.MessageBytes.toBytesSimple(MessageBytes.java:310)
zfile  |        at org.apache.tomcat.util.buf.MessageBytes.toBytes(MessageBytes.java:283)
zfile  |        at org.apache.coyote.http11.Http11OutputBuffer.write(Http11OutputBuffer.java:385)
zfile  |        at org.apache.coyote.http11.Http11OutputBuffer.sendHeader(Http11OutputBuffer.java:364)
zfile  |        at org.apache.coyote.http11.Http11Processor.prepareResponse(Http11Processor.java:1047)
zfile  |        at org.apache.coyote.AbstractProcessor.action(AbstractProcessor.java:377)
zfile  |        at org.apache.coyote.Response.action(Response.java:210)
zfile  |        at org.apache.coyote.Response.sendHeaders(Response.java:453)
zfile  |        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:285)
zfile  |        at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:244)
zfile  |        at org.apache.catalina.connector.Response.finishResponse(Response.java:421)
zfile  |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:373)
zfile  |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
zfile  |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
zfile  |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
zfile  |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
zfile  |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
zfile  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
zfile  |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
zfile  |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
zfile  |        at java.base@23.0.2/java.lang.Thread.runWith(Thread.java:1588)
zfile  |        at java.base@23.0.2/java.lang.Thread.run(Thread.java:1575)
zfile  |        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:837)
zfile  |        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:813)
```

**Comment by tointcn** [comment]
```shell
root@ba83d482e08b:~# locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=C.UTF-8
```

**Comment by tointcn** [comment]
version: 4.3.1

**Comment by zhaojun1998** [comment]
1. 从哪里点击的短链，前台生成还是后台复制。
2. 部署方式？docker 还是本机直接运行。
3. 如果是本机直接运行，操作系统及操作系统版本号。
如果可以的话，麻烦发个异常的短链到我 github 主页左侧邮箱。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年6月16日(周一) 凌晨4:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [zfile-dev/zfile] 文件名称包含中文, 短链 302 跳转无法编码 (Issue #763)




 
Reopened #763.

**Comment by tointcn** [comment]
1. 在前端页面获取的短链

<img width="155" alt="Image" src="https://github.com/user-attachments/assets/a33de802-ecd9-4339-a8d7-b45e60a97bc8" />

2. docker 部署
```
services:
    zfile:
        container_name: zfile
        restart: always
        ports:
            - '6000:8080'
        environment:
            - LANG=C.UTF-8
            - LC_ALL=C.UTF-8
            - TZ=Asia/Shanghai
        volumes:
            - '/data/zfile/db:/root/.zfile-v4/db'
            - '/data/zfile/logs:/root/.zfile-v4/logs'
            - '/data/zfile/file:/data/file'
            - '/data/zfile/application.properties:/root/application.properties'
        image: swr.cn-north-1.myhuaweicloud.com/zfile-dev/zfile:4.3.1
```

3. 好的, 已发送, 请查收.
