### ISSUE TITLE
MYSQL数据库配置

### ISSUE THREAD

**Issue by abiglee** [zfile-dev/zfile#78]
# MySQL 配置
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    #    username: root
    #    password: 123456
小白不懂怎么搞，用“#“注释掉 h2 内存数据库，然后删除mysql配置下面的”#“，新建名为zfile的数据库，用户名root，密码123456？
这样试了，不得行啊

**Comment by lcxw** [comment]
> ```
> # MySQL 配置
> #    driver-class-name: com.mysql.jdbc.Driver
> #    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
> #    username: root
> #    password: 123456
> ```
> 
> 小白不懂怎么搞，用“#“注释掉 h2 内存数据库，然后删除mysql配置下面的”#“，新建名为zfile的数据库，用户名root，密码123456？
> 这样试了，不得行啊

就是下面的配置是设置你的数据库连接，账户和密码
如果不行可以贴日志

**Comment by abiglee** [comment]
> > ```
> > # MySQL 配置
> > #    driver-class-name: com.mysql.jdbc.Driver
> > #    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
> > #    username: root
> > #    password: 123456
> > ```
> > 
> > 
> > 小白不懂怎么搞，用“#“注释掉 h2 内存数据库，然后删除mysql配置下面的”#“，新建名为zfile的数据库，用户名root，密码123456？
> > 这样试了，不得行啊
> 
> 就是下面的配置是设置你的数据库连接，账户和密码
> 如果不行可以贴日志

明天我再试一试

**Comment by lcxw** [comment]
> > > ```
> > > # MySQL 配置
> > > #    driver-class-name: com.mysql.jdbc.Driver
> > > #    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
> > > #    username: root
> > > #    password: 123456
> > > ```
> > > 
> > > 
> > > 小白不懂怎么搞，用“#“注释掉 h2 内存数据库，然后删除mysql配置下面的”#“，新建名为zfile的数据库，用户名root，密码123456？
> > > 这样试了，不得行啊
> > 
> > 
> > 就是下面的配置是设置你的数据库连接，账户和密码
> > 如果不行可以贴日志
> 
> 明天我再试一试

#号代表注释。。

**Comment by abiglee** [comment]
> > > > ```
> > > > # MySQL 配置
> > > > #    driver-class-name: com.mysql.jdbc.Driver
> > > > #    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
> > > > #    username: root
> > > > #    password: 123456
> > > > ```
> > > > 
> > > > 
> > > > 小白不懂怎么搞，用“#“注释掉 h2 内存数据库，然后删除mysql配置下面的”#“，新建名为zfile的数据库，用户名root，密码123456？
> > > > 这样试了，不得行啊
> > > 
> > > 
> > > 就是下面的配置是设置你的数据库连接，账户和密码
> > > 如果不行可以贴日志
> > 
> > 
> > 明天我再试一试
> 
> #号代表注释。。

    # h2 内存数据库 配置
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:~/.zfile/db/zfile
    #    username: zfile
    #    password: 123456

    # MySQL 配置
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
     username: root
     password: 123456

这样改的，

**Comment by Loveyueliang** [comment]
更换为mysql后，提示，`存储策略尚未初始化, 请联系管理员!`
后台查看数据库中建立了两个空的表，没有任何数据
```
 datasource:
    # 初始化数据导入
    data: classpath*:db/data.sql
    sql-script-encoding: utf-8

    initialization-mode: always
    continue-on-error: true

    # h2 内存数据库 配置
    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:~/.zfile/db/zfile
    #username: zfile
    #password: 123456

    # MySQL 配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: zfile
    password: miF2jXKAtPMsTzkh
```
